UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '한국' AND english = 'Korea';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '도시' AND english = 'city';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '이름' AND english = 'name';
UPDATE vocabulary SET category = 'pronoun' WHERE level_number = 1 AND korean = '저' AND english = 'I (formal)';
UPDATE vocabulary SET category = 'pronoun' WHERE level_number = 1 AND korean = '나' AND english = 'I (informal)';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '남자' AND english = 'man';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '여자' AND english = 'woman';
UPDATE vocabulary SET category = 'determiner' WHERE level_number = 1 AND korean = '이' AND english = 'this';
UPDATE vocabulary SET category = 'determiner' WHERE level_number = 1 AND korean = '그' AND english = 'that';
UPDATE vocabulary SET category = 'determiner' WHERE level_number = 1 AND korean = '저' AND english = 'that (far away)';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '것' AND english = 'thing';
UPDATE vocabulary SET category = 'pronoun' WHERE level_number = 1 AND korean = '이것' AND english = 'this thing';
UPDATE vocabulary SET category = 'pronoun' WHERE level_number = 1 AND korean = '그것' AND english = 'that thing';
UPDATE vocabulary SET category = 'pronoun' WHERE level_number = 1 AND korean = '저것' AND english = 'that thing (far away)';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '의자' AND english = 'chair';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '탁자' AND english = 'table';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '선생님' AND english = 'teacher';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '침대' AND english = 'bed';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '집' AND english = 'house';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '차' AND english = 'car';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '사람' AND english = 'person';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '책' AND english = 'book';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '컴퓨터' AND english = 'computer';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '나무' AND english = 'tree';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '소파' AND english = 'sofa';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '지갑' AND english = 'wallet';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '방' AND english = 'room';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '문' AND english = 'door';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '의사' AND english = 'doctor';
UPDATE vocabulary SET category = 'noun' WHERE level_number = 1 AND korean = '학생' AND english = 'student';
