package sengen

type vocabEntry struct {
	Korean  string
	English string
}

var vocabList = []vocabEntry{
	{Korean: "저", English: "I (formal)"},
	{Korean: "나", English: "I (informal)"},
	{Korean: "그녀", English: "she"},
	{Korean: "그", English: "he / that"},
	{Korean: "이", English: "this"},
	{Korean: "학생", English: "student"},
	{Korean: "의사", English: "doctor"},
	{Korean: "선생님", English: "teacher"},
	{Korean: "친구", English: "friend"},
	{Korean: "사람", English: "person"},
	{Korean: "이름", English: "name"},
	{Korean: "책", English: "book"},
	{Korean: "물", English: "water"},
	{Korean: "커피", English: "coffee"},
	{Korean: "음식", English: "food"},
	{Korean: "버스", English: "bus"},
	{Korean: "집", English: "house / home"},
	{Korean: "학교", English: "school"},
	{Korean: "영화", English: "movie"},
	{Korean: "노래", English: "song"},
	{Korean: "날씨", English: "weather"},
	{Korean: "시간", English: "time"},
	{Korean: "오늘", English: "today"},
	{Korean: "내일", English: "tomorrow"},
	{Korean: "어제", English: "yesterday"},
	{Korean: "뭐", English: "what"},
	{Korean: "어디", English: "where"},
	{Korean: "언제", English: "when"},
	{Korean: "누구", English: "who"},
	{Korean: "왜", English: "why"},
	{Korean: "얼마", English: "how much"},
	{Korean: "있다", English: "to have / to exist"},
	{Korean: "없다", English: "to not have / to not exist"},
	{Korean: "가다", English: "to go"},
	{Korean: "오다", English: "to come"},
	{Korean: "만나다", English: "to meet"},
	{Korean: "보다", English: "to see / to watch"},
	{Korean: "듣다", English: "to listen"},
	{Korean: "먹다", English: "to eat"},
	{Korean: "마시다", English: "to drink"},
	{Korean: "하다", English: "to do"},
	{Korean: "말하다", English: "to speak / to say"},
	{Korean: "좋아하다", English: "to like"},
	{Korean: "사다", English: "to buy"},
	{Korean: "읽다", English: "to read"},
	{Korean: "쓰다", English: "to write / to use"},
	{Korean: "배우다", English: "to learn"},
	{Korean: "가르치다", English: "to teach"},
}
