// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddVocabulary implements pgx.CopyFromSource.
type iteratorForAddVocabulary struct {
	rows                 []AddVocabularyParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddVocabulary) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddVocabulary) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LevelNumber,
		r.rows[0].Korean,
		r.rows[0].English,
		r.rows[0].Category,
	}, nil
}

func (r iteratorForAddVocabulary) Err() error {
	return nil
}

func (q *Queries) AddVocabulary(ctx context.Context, arg []AddVocabularyParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"vocabulary"}, []string{"level_number", "korean", "english", "category"}, &iteratorForAddVocabulary{rows: arg})
}

// iteratorForSaveSentences implements pgx.CopyFromSource.
type iteratorForSaveSentences struct {
	rows                 []SaveSentencesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSaveSentences) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSaveSentences) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LevelNumber,
		r.rows[0].Korean,
		r.rows[0].English,
	}, nil
}

func (r iteratorForSaveSentences) Err() error {
	return nil
}

func (q *Queries) SaveSentences(ctx context.Context, arg []SaveSentencesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sentences"}, []string{"level_number", "korean", "english"}, &iteratorForSaveSentences{rows: arg})
}
