// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: levels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLevel = `-- name: CreateLevel :exec
INSERT INTO levels (number, phase_number, grammar_md, exceptions_md)
VALUES ($1, $2, $3, $4)
`

type CreateLevelParams struct {
	Number       int32
	PhaseNumber  int32
	GrammarMd    string
	ExceptionsMd pgtype.Text
}

func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) error {
	_, err := q.db.Exec(ctx, createLevel,
		arg.Number,
		arg.PhaseNumber,
		arg.GrammarMd,
		arg.ExceptionsMd,
	)
	return err
}

const getLevel = `-- name: GetLevel :one
SELECT number, phase_number, grammar_md, COALESCE(exceptions_md, '') AS exceptions_md
FROM levels
WHERE number = $1
`

type GetLevelRow struct {
	Number       int32
	PhaseNumber  int32
	GrammarMd    string
	ExceptionsMd string
}

func (q *Queries) GetLevel(ctx context.Context, number int32) (GetLevelRow, error) {
	row := q.db.QueryRow(ctx, getLevel, number)
	var i GetLevelRow
	err := row.Scan(
		&i.Number,
		&i.PhaseNumber,
		&i.GrammarMd,
		&i.ExceptionsMd,
	)
	return i, err
}

const levelsInPhase = `-- name: LevelsInPhase :many
SELECT number, phase_number, grammar_md, COALESCE(exceptions_md, '') AS exceptions_md
FROM levels
WHERE phase_number = $1
ORDER BY number
`

type LevelsInPhaseRow struct {
	Number       int32
	PhaseNumber  int32
	GrammarMd    string
	ExceptionsMd string
}

func (q *Queries) LevelsInPhase(ctx context.Context, phaseNumber int32) ([]LevelsInPhaseRow, error) {
	rows, err := q.db.Query(ctx, levelsInPhase, phaseNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LevelsInPhaseRow
	for rows.Next() {
		var i LevelsInPhaseRow
		if err := rows.Scan(
			&i.Number,
			&i.PhaseNumber,
			&i.GrammarMd,
			&i.ExceptionsMd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const levelsUpTo = `-- name: LevelsUpTo :many
SELECT number, phase_number, grammar_md, COALESCE(exceptions_md, '') AS exceptions_md
FROM levels
WHERE number <= $1
ORDER BY number
`

type LevelsUpToRow struct {
	Number       int32
	PhaseNumber  int32
	GrammarMd    string
	ExceptionsMd string
}

func (q *Queries) LevelsUpTo(ctx context.Context, number int32) ([]LevelsUpToRow, error) {
	rows, err := q.db.Query(ctx, levelsUpTo, number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LevelsUpToRow
	for rows.Next() {
		var i LevelsUpToRow
		if err := rows.Scan(
			&i.Number,
			&i.PhaseNumber,
			&i.GrammarMd,
			&i.ExceptionsMd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLevelNumber = `-- name: MaxLevelNumber :one
SELECT COALESCE(MAX(number), 0) FROM levels
`

func (q *Queries) MaxLevelNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, maxLevelNumber)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateLevel = `-- name: UpdateLevel :exec
UPDATE levels SET grammar_md = $2, exceptions_md = $3 WHERE number = $1
`

type UpdateLevelParams struct {
	Number       int32
	GrammarMd    string
	ExceptionsMd pgtype.Text
}

func (q *Queries) UpdateLevel(ctx context.Context, arg UpdateLevelParams) error {
	_, err := q.db.Exec(ctx, updateLevel, arg.Number, arg.GrammarMd, arg.ExceptionsMd)
	return err
}
