// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Level struct {
	Number       int32
	PhaseNumber  int32
	GrammarMd    string
	ExceptionsMd pgtype.Text
}

type Phase struct {
	Number int32
	Name   string
}

type Sentence struct {
	ID          int32
	LevelNumber int32
	Korean      string
	English     string
	CreatedAt   pgtype.Timestamptz
}

type Vocabulary struct {
	ID          int32
	LevelNumber int32
	Korean      string
	English     string
}
