// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phases.sql

package db

import (
	"context"
)

const createPhase = `-- name: CreatePhase :exec
INSERT INTO phases (number, name) VALUES ($1, $2)
`

type CreatePhaseParams struct {
	Number int32
	Name   string
}

func (q *Queries) CreatePhase(ctx context.Context, arg CreatePhaseParams) error {
	_, err := q.db.Exec(ctx, createPhase, arg.Number, arg.Name)
	return err
}

const getPhase = `-- name: GetPhase :one
SELECT number, name FROM phases WHERE number = $1
`

func (q *Queries) GetPhase(ctx context.Context, number int32) (Phase, error) {
	row := q.db.QueryRow(ctx, getPhase, number)
	var i Phase
	err := row.Scan(&i.Number, &i.Name)
	return i, err
}

const listPhases = `-- name: ListPhases :many
SELECT number, name FROM phases ORDER BY number
`

func (q *Queries) ListPhases(ctx context.Context) ([]Phase, error) {
	rows, err := q.db.Query(ctx, listPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Phase
	for rows.Next() {
		var i Phase
		if err := rows.Scan(&i.Number, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhase = `-- name: UpdatePhase :exec
UPDATE phases SET name = $2 WHERE number = $1
`

func (q *Queries) UpdatePhase(ctx context.Context, number int32, name string) error {
	_, err := q.db.Exec(ctx, updatePhase, number, name)
	return err
}

const maxPhaseNumber = `-- name: MaxPhaseNumber :one
SELECT COALESCE(MAX(number), 0) FROM phases
`

func (q *Queries) MaxPhaseNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, maxPhaseNumber)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
