// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentences.sql

package db

type SaveSentencesParams struct {
	LevelNumber int32
	Korean      string
	English     string
}
